<!DOCTYPE html>
<html>

<head>
    <title>Lógica de Programação JavaScript</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
</head>

<body>
    <h1>Lógica de Programação JavaScript</h1>

    <button onclick="iniciarCalculo('+')">+</button>
    <button onclick="iniciarCalculo('-')">-</button>
    <button onclick="iniciarCalculo('*')">*</button>
    <button onclick="iniciarCalculo('/')">/</button>

    <div id="output"></div>

    <script>

        var n2 = prompt('digite um número');
        n2 = parseFloat(n2);

        escreve(n2);

        function iniciarCalculo(simbolo) {
            var n1 = document.querySelector("#output").textContent;
            n1 = parseFloat(n1);

            var n2 = prompt("digite outro número:");
            n2 = parseFloat(n2);

            /* Try... Catch(erro) 

        Tratam da exceção.
        Não deveria ter ocorrido, mas ocorreu.
        Nunca subestime a capacidade do usuário. */


            try {

                var msg = calcular(simbolo, n1, n2);

            } catch (e) {
                alert(e);
                return;
            }

            escreve(msg);
        }

        function escreve(mensagem) {
            var output = document.querySelector("#output")
            output.innerHTML = mensagem;
        }

        function calcular(simbolo, n1, n2) {

            if (isNaN(n1) || isNaN(n2)) {
                throw new Error("digitar somente números");

            }

            var numeroCalculado = null;

            switch (simbolo) {
                case '+':
                    numeroCalculado = n1 + n2;
                    break;

                case '-':
                    numeroCalculado = n1 - n2;
                    break;

                case '*':
                    numeroCalculado = n1 * n2;
                    break;

                case '/':
                    numeroCalculado = n1 / n2;

            }

            return numeroCalculado;
        }




    </script>
</body>

</html>